### ISSUE TITLE
exception running on non-git folders

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#100] opened 2019-10-15 16:09 UTC
Make sure you are running the latest version of Bento.

**Describe the bug**
Bento throws an exception when running on a directory that doesn't have a `.git` 

**Expected result**
Bento either tells me that non-git repositories aren't supported, or just runs on the current directory.

**Actual result**
```
git.exc.InvalidGitRepositoryError: ~/Documents/sqli-example
✘ There was an exception ~/Documents/sqli-example
```

**Additional context**
`bento/0.1.0r6`

**Comment by nbrahms** [comment] 2019-10-15 21:09
Thanks for the report, @ievans .

We've fixed this as of 0.1.1b4.

**Comment by arashd** [comment] 2019-10-15 23:36
This doesn't seem to be working for me on `bento/0.1.1b4`
```bash
bento init
Creating default configuration at .bento.yml
✔ Created .bento.yml. Please check this file in to source control.

Detected project with Python

✔ Creating virtual environment for r2c.bandit
✔ Python package bandit will be installed
✔ Creating virtual environment for r2c.flake8
✔ Python package flake8 will be installed
✔ Python package flake8-json will be installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/__main__.py", line 14, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 541, in init
    r = bento.metrics.__get_git_repo()
  File "/usr/local/lib/python3.7/site-packages/bento/metrics.py", line 14, in __get_git_repo
    r = git.Repo(dirPath, search_parent_directories=True)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 183, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/arashdelijani/workspace/bento-tests/some-dir
✘ There was an exception /Users/arashdelijani/workspace/bento-tests/some-dir
```

**Comment by arashd** [comment] 2019-10-15 23:36
removing the fixed flag so it gets our attention.

**Comment by nbrahms** [comment] 2019-10-16 00:16
Now fixed in 0.1.1b5.

**Comment by arashd** [comment] 2019-10-16 08:43
👍 can we link to pending issues from the corresponding PRs that fix them? Just for easier reference since GH nicely creates references in both directions.

**Comment by arashd** [comment] 2019-10-16 20:30
confirmed that this works in `bento/0.1.1b6`; closing.

**Closed by arashd** 2019-10-16 20:30 UTC
Labels: bug, fixed, priority:high, priority:release-blocking
