### ISSUE TITLE
Timeout when checking latest version

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#218] opened 2019-12-12 22:20 UTC
## Overview
When tailing the latest log in `~/.bento/last.log`, Bento times out after 0.25 seconds (very frequently when on a slow connection)

## Current Behavior
> Describe the actual behavior, and provide the content of `~/.bento/last.log` if possible. Screenshots and text dumps are particularly helpful.

```
[INFO] 154.27589416503906 root:cli - Python version is (3.7)
[INFO] 155.82275390625 root:register - User ToS agreement is current
[DEBUG] 449.4318962097168 urllib3.connectionpool:connectionpool - Starting new HTTPS connection (1): bento.r2c.dev:443
[ERROR] 747.7667331695557 root:network - HTTPSConnectionPool(host='bento.r2c.dev', port=443): Read timed out. (read timeout=0.25)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1059: The handshake operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 379, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bento.r2c.dev', port=443): Read timed out. (read timeout=0.25)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/network.py", line 83, in fetch_latest_version
    r = no_auth_get(url, timeout=0.25)
  File "/usr/local/lib/python3.7/site-packages/bento/network.py", line 56, in no_auth_get
    url, headers=headers, params=params, **{"timeout": TIMEOUT, **kwargs}
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bento.r2c.dev', port=443): Read timed out. (read timeout=0.25)
[INFO] 751.6849040985107 root:cli - Current bento version is 0.7.0b7, latest is None
[INFO] 752.539873123169 root:base_context - Loading bento configuration from /Users/arashdelijani/workspace/bento-tests/instabot/.bento.yml
[INFO] 766.0839557647705 root:base_context - Writing bento configuration to /Users/arashdelijani/workspace/bento-tests/instabot/.bento.yml
[INFO] 770.9369659423828 root:util - 'A002' enabled for 'r2c.flake8'
```

## Steps to Reproduce

1. run any bento command on a slow connection
2. see Bento logs

## Possible Solution
> Increasing the timeout of the request?

## Additional Context
Bento version (run `bento --version`):
Operation system (e.g. Ubuntu 18.04):
Any other context that would help us reproduce or understand the issue:

**Comment by nbrahms** [comment] 2019-12-16 19:55
Hi @arashd 

This is actually intended behavior, as we don't want to block the user on a slow response.

Would you be able to recast this into a feature request that you would desire?

**Comment by dlukeomalley** [comment] 2019-12-18 00:43
Closing for `wont-fix` for now. Let's all catch-up offline to discuss possible FRs around this observation.

**Closed by dlukeomalley** 2019-12-18 00:43 UTC
Labels: wont-fix
