### ISSUE TITLE
Make it clearer that archive is checked in

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#74] opened 2019-10-10 01:58 UTC
User says:
> The archive is a key feature, but it needs to be managed by source control and support user annotations, i.e.: when I submit a PR I can submit an updated archive entry too that whitelist some obnoxious warning.

Let's improve messaging to tell users why and when they should use archive. It's apparently not clear that it's: 
1. checked in to source control
2. not meant for hiding obnoxious warnings, but instead delaying tech-debt. Is it the word "archive" that's misleading here?

**Comment by nbrahms** [comment] 2019-10-14 17:31
Hi @arashd 

Currently, the tool (as of 0.1.1b1) emits the following text:
```
✔ Rewrote the whitelist with ... findings from ... tools (... new, ... previously whitelisted).
  Please check '.bento-whitelist.yml' in to source control.
```

Is there more that you were looking for?

**Comment by arashd** [comment] 2019-10-18 20:33
I filed this so we improve documentation, so I'll remove the fixed label and self-assign.

**Comment by dlukeomalley** [comment] 2019-11-01 04:21
Closing as a duplicate of #91. Thank you @arashd for the ticket!

**Closed by dlukeomalley** 2019-11-01 04:21 UTC
Labels: command:archive, documentation, duplicate
