### ISSUE TITLE
Make a more graceful failure when `bento init` is run from non-git directory

### ISSUE THREAD

**Issue by embailie** [returntocorp/bento#108] opened 2019-10-15 21:56 UTC
**Is your feature request related to a problem? Please describe.**
Currently, if `bento init` is run from from a non-git directory, the init will run for several seconds and fail without a clear bento statement.  

**Describe the solution you'd like**
Bento could run a check to verify the directory is a git repository, and if it isn't, provide a helpful message directing the user where to run bento from. 

-------

```
bento init
Creating default configuration at .bento.yml
✔ Created .bento.yml. Please check this file in to source control.

Detected project with Python

✔ Creating virtual environment for r2c.bandit
✔ Python package bandit will be installed
✔ Creating virtual environment for r2c.flake8
✔ Python package flake8 will be installed
✔ Python package flake8-json will be installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/__main__.py", line 14, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 541, in init
    r = bento.metrics.__get_git_repo()
  File "/usr/local/lib/python3.7/site-packages/bento/metrics.py", line 14, in __get_git_repo
    r = git.Repo(dirPath, search_parent_directories=True)
  File "/usr/local/lib/python3.7/site-packages/git/repo/base.py", line 183, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/erinbailie/workspace
✘ There was an exception /Users/erinbailie/workspace
```

**Comment by nbrahms** [comment] 2019-10-16 16:10
Closing this as a duplicate of #100

**Closed by nbrahms** 2019-10-16 16:10 UTC
