### ISSUE TITLE
Bento doesn't find JS files

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#51] opened 2019-10-08 21:06 UTC
Ran bento on commit b196bd3c9ff7bc31ea33316792db30b755b0c2ba of https://github.com/microsoft/project-python-django-webapp

There are JS files in static/ but bento doesn't find them.

**Comment by arashd** [comment] 2019-10-08 21:31
further conversation revealed: we only detect JS if there's a package.json file at the moment. How can we change language to reflect this while also conveying the idea of multi-language support?

**Comment by nbrahms** [comment] 2019-10-08 22:43
This appears to be a duplicate of #29. Closing in favor of the original issue.

**Closed by nbrahms** 2019-10-08 22:43 UTC
Labels: bug, duplicate
