### ISSUE TITLE
bento check reports commited-thus-ignored findings as "archived"

### ISSUE THREAD

**Issue by underyx** [returntocorp/bento#313] opened 2020-04-01 13:56 UTC
## Current Behavior

When there's an already committed finding in a find that `bento check` scans, Bento prints this output

```
Running Bento checks on staged files...

hadolint․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
shellcheck․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done

✔ 0 findings due to staged changes in 1.45 s
◦ Not showing 1 archived finding(s). To view, run $ cat .bento/archive.json
```

- The finding is not actually archived.
- `.bento/archive.json` will usually not actually exist, so the recommended command will fail.

## Steps to Reproduce

1. Commit a bento finding
2. Stage a harmless change to some other lines in the same file
3. Run `bento check`

## Possible Solution

When `bento check` is ignoring findings, exclude the count from the "Not showing N archived findings" line, or add a line that says "Not showing N pre-existing findings". Though note that bento will be running on only a few files, so this number fluctuating a lot might confuse people.
 
## Additional Context

Bento version (run `bento --version`): bento/0.10.1
Operating system (e.g., Ubuntu 18.04): macOS 10.14

**Comment by dlukeomalley** [comment] 2020-04-01 14:35
@underyx This sounds like a duplicate of #258. Up for squashing these issues?

**Closed** 2020-04-24 23:30 UTC
Labels: bug, duplicate
