### ISSUE TITLE
No section user

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/bento#113] opened 2019-10-15 23:39 UTC
Make sure you are running the latest version of Bento.

**Describe the bug**
Describe the issue briefly here.
Bug running bento (Daghan's bug)
**Expected result**
Describe what you expected to see.
Success

**Actual result**
When possible, provide verbose output (--verbose)

```Do you agree to Bento’s terms of service and privacy policy? [Y/n]:
For the Bento beta, may we contact you infrequently via email to ask for your feedback and let you know about updates? You can unsubscribe at any time. [Y/n]: Y
Traceback (most recent call last):
 File “/usr/local/lib/python3.7/site-packages/bento/__main__.py”, line 14, in main
   cli()
 File “/usr/local/lib/python3.7/site-packages/click/core.py”, line 764, in __call__
   return self.main(*args, **kwargs)
 File “/usr/local/lib/python3.7/site-packages/click/core.py”, line 717, in main
   rv = self.invoke(ctx)
 File “/usr/local/lib/python3.7/site-packages/click/core.py”, line 1134, in invoke
   Command.invoke(self, ctx)
 File “/usr/local/lib/python3.7/site-packages/click/core.py”, line 956, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File “/usr/local/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
   return callback(*args, **kwargs)
 File “/usr/local/lib/python3.7/site-packages/bento/cli.py”, line 443, in cli
   registered = register_user()
 File “/usr/local/lib/python3.7/site-packages/bento/cli.py”, line 388, in register_user
   “Email”, type=str, default=bento.metrics.__get_git_user_email()
 File “/usr/local/lib/python3.7/site-packages/bento/metrics.py”, line 23, in __get_git_user_email
   return r.config_reader().get_value(“user”, “email”)
 File “/usr/local/lib/python3.7/site-packages/git/config.py”, line 590, in get_value
   valuestr = self.get(section, option)
 File “/usr/local/lib/python3.7/site-packages/git/config.py”, line 79, in assure_data_present
   return func(self, *args, **kwargs)
 File “/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py”, line 780, in get
   d = self._unify_values(section, vars)
 File “/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py”, line 1146, in _unify_values
   raise NoSectionError(section) from None
configparser.NoSectionError: No section: ‘user’
✘ There was an exception No section: ‘user’
daghan-loan:serverside_js daghan$ bento --version
bento/0.1.1b4```

**Additional context**
Let us know additional context like the version of Bento you're using (--version), your OS, relevant information about the project you're checking with Bento, if you have existing linters set up, and other information that might help us reproduce the issue. Screenshots are usually helpful, too.

**Comment by DrewDennison** [comment] 2019-10-15 23:40
thanks @daghan for the stack trace

**Comment by nbrahms** [comment] 2019-10-16 16:12
Closing as a duplicate of #107

**Closed by nbrahms** 2019-10-16 16:12 UTC
Labels: bug
