### ISSUE TITLE
Bento shows upgrade prompt despite no available upgrades

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#72] opened 2019-10-10 00:41 UTC
Two users on `bento-cli` on `bento/0.1.0` are told on every command that a new version of Bento is available to upgrade to. It is not...

> Even though I just installed it, it keeps telling me there is a new version of bento available (there isn’t).

> it keeps telling me there is a new version available
> but I run the command to upgrade and it doesn't upgrade
> your code is hitting this endpoint to get the latest version:
> https://test.massive.ret2.co/bento/api/v1/version
> it says 0.1.0.post6

CC: @dmontagu

**Comment by dlukeomalley** [comment] 2019-10-10 00:47
I've marked this issue as `priority:high` because it's distracting to users and leads them to attempt an upgrade when none is available. Worth a quick fix.

**Comment by dmontagu** [comment] 2019-10-10 01:09
Yeah, I think the problem is that pip installs 0.1.0, the endpoint returns 0.1.0.post6, and the `bento.cli.is_running_latest` function says 0.1.0.post6 is newer (as it maybe should?).

------

Also, that function will probably need to be modified at some point soon:

```python
def is_running_latest() -> bool:
    latest_version, _ = network.fetch_latest_version()
    if latest_version and get_version() < latest_version:
        return False
    return True
```
both `latest_version` and the result of `get_version()` are currently raw version strings. So, for example, you'll run into issues like:

```
>>> "0.2.0" < "0.11.0"
False
```

**Comment by brendongo** [comment] 2019-10-10 01:15
The endpoint was checking the latest version of a different package which we have no fixed to use the correct package so it should be correctly returning 0.1.0. Good catch on the raw version string I'll get that fixed right away.

**Comment by brendongo** [comment] 2019-10-10 01:23
I have opened #73 to track the version comparison issue @dmontagu. Closing this issue cause I believe this is fixed @dlukeomalley

**Closed by brendongo** 2019-10-10 01:23 UTC
Labels: bug, priority:high

**Comment by dmontagu** [comment] 2019-10-11 09:33
@brendongo This error is happening again -- looks like its pointing at `0.1.0.post1` now.

**Comment by dlukeomalley** [comment] 2019-10-11 16:14
@dmontagu There is a new release available with bug fixes. Please upgrade by running `pip3 install --upgrade bento-cli`
