### ISSUE TITLE
eslint crashing on jsx file

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#105] opened 2019-10-15 21:31 UTC
Make sure you are running the latest version of Bento.

**Describe the bug**
`bento check` is broken and I'm not sure what the error means, but it's in a jsx file.

**Expected result**
`bento check` produces eslint results or tells me it doesn't support jsx.

**Actual result**
```bash
bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:01, 🍱
  r2c.eslint: |███████        | 00:03, 🍤
  r2c.flake8: |███████████████| 00:03, 🍱

✘ Error while running r2c.eslint: Command '['./node_modules/eslint/bin/eslint.js', '--no-eslintrc', '-c', '.eslintrc.yml', '-f', 'json', '--ignore-pattern', '**/node_modules', '--ext', 'js,jsx,ts,tsx', '.']' returned non-zero exit status 2.
TypeError: Cannot read property 'match' of undefined
Occurred while linting /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/src/index.jsx:1
    at countTrailingLinebreaks (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:792:47)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:859:65
    at Array.forEach (<anonymous>)
    at addElementListIndent (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:834:22)
    at Object.addFunctionCallIndent [as listener] (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:927:13)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:1585:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:1585:26)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)



server.py
 14:0  error   A Flask app appears to be run with debug=True, which exposes the Werkzeug debugger and allows the... r2c.bandit     B201

⚠ 1 findings in 3.28 s

To suppress all findings run `bento archive`.
```

**Additional context**
$ bento --version
bento/0.1.1b4

running on `minimal-flask-react@f070c9d53`

**Comment by nbrahms** [comment] 2019-10-16 16:13
This seems to be a duplicate of #66

**Closed by nbrahms** 2019-10-16 16:13 UTC
Labels: bug
