### ISSUE TITLE
Bento tries to update ESLint every time I run bento check

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#5] opened 2019-09-30 21:58 UTC
I cloned the [Zulip repo](https://github.com/zulip/zulip) and ran `bento setup`.

Bento successfully configured after updating (or trying to update) a bunch of dependencies.

Then I ran `bento check` and Bento seems to try to do its setup again:
<img width="948" alt="Screen Shot 2019-09-30 at 2 56 12 PM" src="https://user-images.githubusercontent.com/302941/65919905-7ccc3980-e392-11e9-9817-4f7f39d56e42.png">

Part way through the process, I am asked about using Yarn to install dependencies, and it seems to be happening right on top of flake8 analysis:
<img width="649" alt="Screen Shot 2019-09-30 at 2 57 33 PM" src="https://user-images.githubusercontent.com/302941/65919975-a84f2400-e392-11e9-8e3a-d14a7e802009.png">

^^^ at this point it seems Bento is paused and waiting for my input before continuing.

**Comment by nbrahms** [comment] 2019-10-01 17:14
This seems related to issue #10, caused by `npx install-peerdeps` using `yarn` for installation rather than `npm`.

I'm closing this as a duplicate, and we'll track all progress in #10.

**Closed by nbrahms** 2019-10-01 17:14 UTC
Labels: duplicate
